schemaVersion: 2.2.0
metadata:
  name: java-springboot-intellij
components:
  - name: springboot-dev
    container:
      sourceMapping: /projects
      memoryLimit: 6144Mi
      memoryRequest: 2048Mi
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      image: registry.redhat.io/devspaces/udi-rhel8
      endpoints:
        - name: flights
          exposure: public
          targetPort: 8080
          protocol: https
          path: /api/v1/flights
      env:
        - name: CHE_PLUGIN_REGISTRY_URL
          value: https://devspaces.apps.sandbox-m3.1530.p1.openshiftapps.com/plugin-registry/v3
          # value: https://open-vsx.org
  - name: m2
    volume:
      size: 2Gi
commands:
  - exec:
      commandLine: ./gradlew clean build
      component: springboot-dev
      workingDir: '/projects/devspaces'
      label: Start Quarkus in Dev Mode (getting-started)
    id: springboot-dev-mode
  - exec:
      commandLine: ./gradlew bootRun
      component: springboot-dev
      workingDir: '/projects/devspaces'
      label: Start Quarkus in Dev Mode (getting-started)
    id: springboot-dev-mode  
